use alloy_primitives::{Address, Bytes, FixedBytes, U256};
use alloy_sol_types::SolCall;
use std::fmt;

// ---------------------------------------------------------------------------
// ABI type bindings — generated from the forge artifact via build.rs
// ---------------------------------------------------------------------------

alloy_sol_macro::sol!(
    EntityRegistry,
    "execute_abi.json"
);

pub use EntityRegistry::executeCall;

// Struct types generated by sol! from `internalType` references.
// EntityHashing.Op / EntityHashing.Attribute come from the library namespace.
// Mime128 is a top-level struct (no library prefix in its internalType).
use EntityHashing::{Attribute, Op};
use EntityRegistry::Mime128;

// Op type constants (from EntityHashing.sol).
pub const CREATE: u8 = 0;
pub const UPDATE: u8 = 1;
pub const EXTEND: u8 = 2;
pub const TRANSFER: u8 = 3;
pub const DELETE: u8 = 4;
pub const EXPIRE: u8 = 5;

// ---------------------------------------------------------------------------
// Scenario descriptor
// ---------------------------------------------------------------------------

#[derive(Clone)]
pub struct Scenario {
    pub label: String,
    pub op_type: u8,
    pub payload_size: usize,
    pub attr_count: usize,
    pub batch_size: usize,
    pub new_block: bool,
    pub keccak_pct: u8, // 0..=100, percentage of mainnet keccak cost
    /// Pre-encoded calldata for `execute(Op[])`.
    pub calldata: Bytes,
}

impl fmt::Display for Scenario {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            f,
            "{:<8} | payload={:>5}B | attrs={:>2} | batch={:>2} | {} | keccak={}%",
            op_name(self.op_type),
            self.payload_size,
            self.attr_count,
            self.batch_size,
            if self.new_block { "new_block" } else { "same_blk " },
            self.keccak_pct,
        )
    }
}

fn op_name(t: u8) -> &'static str {
    match t {
        CREATE => "CREATE",
        UPDATE => "UPDATE",
        EXTEND => "EXTEND",
        TRANSFER => "TRANSFER",
        DELETE => "DELETE",
        EXPIRE => "EXPIRE",
        _ => "UNKNOWN",
    }
}

// ---------------------------------------------------------------------------
// Scenario construction
// ---------------------------------------------------------------------------

/// Build the scenario list to profile.
pub fn build_all() -> Vec<Scenario> {
    // Max-stuffed transaction: 32 attributes (each with full bytes32[4]
    // values), payload fills remaining calldata budget.
    //
    // Calldata cost: 16 gas per non-zero byte, 4 per zero.
    // Block gas limit: 30M. Intrinsic tx cost: 21,000.
    // Budget for calldata gas ≈ 30M - 21K - execution overhead.
    //
    // Compute fixed overhead: encode with empty payload, measure size.
    let empty = encode_execute(&[make_create_op(0, 32)]);
    let overhead = empty.len();

    // Estimate max calldata: assume ~1M gas execution overhead,
    // all non-zero bytes (16 gas each).
    // (30_000_000 - 21_000 - 1_000_000) / 16 = ~1,811,187 bytes total calldata
    let max_calldata = (30_000_000u64 - 21_000 - 1_000_000) / 16;
    let max_payload = (max_calldata as usize).saturating_sub(overhead);

    // Round payload down to 32-byte boundary for clean ABI encoding.
    let max_payload = (max_payload / 32) * 32;

    eprintln!("ABI overhead (0-byte payload): {} bytes", overhead);
    eprintln!("Max calldata budget:           {} bytes", max_calldata);
    eprintln!("Max payload:                   {} bytes", max_payload);
    eprintln!();

    vec![build_create_scenario(max_payload, 32, 1, true, 100)]
}

fn build_create_scenario(
    payload_size: usize,
    attr_count: usize,
    batch_size: usize,
    new_block: bool,
    keccak_pct: u8,
) -> Scenario {
    let op = make_create_op(payload_size, attr_count);
    let ops = vec![op; batch_size];
    let calldata = encode_execute(&ops);

    Scenario {
        label: format!("create_p{}_a{}_b{}", payload_size, attr_count, batch_size),
        op_type: CREATE,
        payload_size,
        attr_count,
        batch_size,
        new_block,
        keccak_pct,
        calldata,
    }
}

fn build_update_scenario(
    payload_size: usize,
    attr_count: usize,
    batch_size: usize,
    new_block: bool,
    keccak_pct: u8,
) -> Scenario {
    // UPDATE requires an existing entityKey — the profiler must CREATE first,
    // then replay with this calldata. We use a placeholder key here; the
    // profiler fills it in after deployment + creation.
    let op = make_update_op(FixedBytes::ZERO, payload_size, attr_count);
    let ops = vec![op; batch_size];
    let calldata = encode_execute(&ops);

    Scenario {
        label: format!("update_p{}_a{}_b{}", payload_size, attr_count, batch_size),
        op_type: UPDATE,
        payload_size,
        attr_count,
        batch_size,
        new_block,
        keccak_pct,
        calldata,
    }
}

fn build_fixed_op_scenario(
    op_type: u8,
    batch_size: usize,
    new_block: bool,
    keccak_pct: u8,
) -> Scenario {
    let op = make_fixed_op(op_type, FixedBytes::ZERO);
    let ops = vec![op; batch_size];
    let calldata = encode_execute(&ops);

    Scenario {
        label: format!("{}_{}", op_name(op_type).to_lowercase(), batch_size),
        op_type,
        payload_size: 0,
        attr_count: 0,
        batch_size,
        new_block,
        keccak_pct,
        calldata,
    }
}

// ---------------------------------------------------------------------------
// Op construction helpers
//
// Field types match the ABI (generated from artifact via build.rs):
//   contentType → Mime128 { data: bytes32[4] }
//   Attribute.value → bytes32[4]  (fixed 128-byte container)
//   expiresAt → uint32            (BlockNumber UDVT unwraps to uint32)
// ---------------------------------------------------------------------------

fn make_create_op(payload_size: usize, attr_count: usize) -> Op {
    Op {
        opType: CREATE,
        entityKey: FixedBytes::ZERO,
        payload: Bytes::from(vec![0xAB; payload_size]),
        contentType: make_mime128(),
        attributes: make_attributes(attr_count),
        expiresAt: u32::MAX, // far future
        newOwner: Address::ZERO,
    }
}

fn make_update_op(entity_key: FixedBytes<32>, payload_size: usize, attr_count: usize) -> Op {
    Op {
        opType: UPDATE,
        entityKey: entity_key,
        payload: Bytes::from(vec![0xCD; payload_size]),
        contentType: make_mime128(),
        attributes: make_attributes(attr_count),
        expiresAt: 0,
        newOwner: Address::ZERO,
    }
}

fn make_fixed_op(op_type: u8, entity_key: FixedBytes<32>) -> Op {
    Op {
        opType: op_type,
        entityKey: entity_key,
        payload: Bytes::new(),
        contentType: Mime128 { data: [FixedBytes::ZERO; 4] },
        attributes: vec![],
        expiresAt: if op_type == EXTEND { u32::MAX } else { 0 },
        newOwner: if op_type == TRANSFER {
            Address::from([0x02; 20])
        } else {
            Address::ZERO
        },
    }
}

/// Encode a valid Mime128: "application/json" left-aligned in bytes32[4].
/// Matches Solidity's encodeMime128: each byte stored at word[j] position,
/// zero-padded to the right.
fn make_mime128() -> Mime128 {
    let mut data = [FixedBytes::ZERO; 4];
    let mime = b"application/json";
    let mut buf = [0u8; 128];
    buf[..mime.len()].copy_from_slice(mime);
    for i in 0..4 {
        let start = i * 32;
        let mut word = [0u8; 32];
        word.copy_from_slice(&buf[start..start + 32]);
        data[i] = FixedBytes::from(word);
    }
    Mime128 { data }
}

/// Build `count` valid attributes with deterministic sorted Ident32 names.
fn make_attributes(count: usize) -> Vec<Attribute> {
    (0..count)
        .map(|i| {
            // Name: left-aligned ASCII identifier, sorted by construction.
            // "a00\0...", "a01\0...", ... "a31\0..."
            let mut name_bytes = [0u8; 32];
            let label = format!("a{:02}", i);
            name_bytes[..label.len()].copy_from_slice(label.as_bytes());
            let name = FixedBytes::from(name_bytes);

            // Value: ATTR_UINT (type 0), value as uint256 in slot 0.
            let mut value = [FixedBytes::ZERO; 4];
            value[0] = FixedBytes::from(U256::from(i).to_be_bytes::<32>());

            Attribute {
                name,
                valueType: 0, // ATTR_UINT
                value,
            }
        })
        .collect()
}

// ---------------------------------------------------------------------------
// ABI encoding — uses generated executeCall for correct selector
// ---------------------------------------------------------------------------

/// ABI-encode `execute(Op[])` calldata including the 4-byte selector.
fn encode_execute(ops: &[Op]) -> Bytes {
    let call = executeCall {
        ops: ops.to_vec(),
    };
    Bytes::from(call.abi_encode())
}
